In [24]:
import pandas as pd

In [25]:
# Create dataframe
data = pd.read_csv("https://raw.githubusercontent.com/dhamvi01/Univariate-Time-Series-using-LSTM/master/airline-passengers.csv")
data

       Month  Passengers
0    1949-01         112
1    1949-02         118
2    1949-03         132
3    1949-04         129
4    1949-05         121
..       ...         ...
139  1960-08         606
140  1960-09         508
141  1960-10         461
142  1960-11         390
143  1960-12         432

[144 rows x 2 columns]

In [26]:
Month = data.values[:, :1]
Passengers = data.values[:, 1]

In [27]:
from numpy import array
# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
  Month, Passengers = list(), list()
  for i in range(len(sequence)):
    # find the end of this pattern
    end_ix = i + n_steps
    # check if we are beyond the sequence
    if end_ix > len(sequence)-1:
      break
  # gather input and output parts of the pattern
    seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
    Month.append(seq_x)
    Passengers.append(seq_y)
  return array(Month), array(Passengers)

Month,Passengers = split_sequence(Passengers, 3)

In [28]:
import pandas as pd
column_names = ["Xt-2","Xt-1","Xt"]
df = pd.DataFrame(Month,Passengers, columns=column_names)
df.head()

    Xt-2 Xt-1   Xt
129  112  118  132
121  118  132  129
135  132  129  121
148  129  121  135
148  121  135  148

In [29]:
df.to_csv('/content/drive/MyDrive/prosaindata/tugas/timeseries.csv',index=False)

In [54]:
from sklearn.preprocessing import MinMaxScaler

df = pd.read_csv('/content/drive/MyDrive/prosaindata/tugas/timeseries.csv', usecols=[1], engine='python')
scaler = MinMaxScaler()
#scaler.fit(features)
#scaler.transform(features)
scaled = scaler.fit_transform(df)
features_names = df.columns.copy()
#features_names.remove('label')
scaled_features = pd.DataFrame(scaled, columns=features_names)
scaled_features

         Xt-1
0    0.027027
1    0.054054
2    0.048263
3    0.032819
4    0.059846
..        ...
136  0.832046
137  1.000000
138  0.969112
139  0.779923
140  0.689189

[141 rows x 1 columns]